---
# Per environment values which override defaults in hmpps-digital-canteen-ui/values.yaml

generic-service:
  replicaCount: 1

  ingress:
    host: pin-phone-ui-preprod.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://pin-phone-ui-preprod.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    LAUNCHPAD_AUTH_URL: "https://launchpad-auth-preprod.hmpps.service.justice.gov.uk"
    LAUNCHPAD_URL: "https://launchpad-home-preprod.hmpps.service.justice.gov.uk"
    PRISONER_APPS_URL: "https://prisoner-apps-preprod.hmpps.service.justice.gov.uk/"
    PIN_PHONE_API_URL: "https://pin-phone-preprod.prison.service.justice.gov.uk"
    ENVIRONMENT_NAME: PREPROD
    SHUTTER_ENABLED: "true"
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  businessHoursOnly: true
  alertSeverity: hmpps-pin-phone-preprod
